version: '3'

services:
  weather-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - tile38
  tile38:
    image: tile38/tile38
    ports:
      - "9851:9851"
  redis:
    image: redis
    ports:
      - "6379:6379"
  
